/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CAGUI;
import carnetaddresse.DataBase;
import carnetaddresse.Personne;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Administrator
 */
public class Formulaire extends javax.swing.JFrame {

    /**
     * Creates new form Formulaire
     */
    List<Personne> joueurs= new ArrayList<Personne>();
    DataBase dbinstence = new DataBase("joueurs.tmp");
    DefaultTableModel model;
    private int row;
    private Personne selectedPersonne;
    public Formulaire() {
        initComponents();
        this.fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lnom = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        lprenom = new javax.swing.JLabel();
        prenom = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(3, 1));

        jPanel1.setLayout(new java.awt.GridLayout(5, 2));

        lnom.setFont(new java.awt.Font("Imprint MT Shadow", 3, 18)); // NOI18N
        lnom.setText("NOM");
        jPanel1.add(lnom);
        jPanel1.add(nom);

        lprenom.setFont(new java.awt.Font("Imprint MT Shadow", 3, 18)); // NOI18N
        lprenom.setText("PRENOM");
        jPanel1.add(lprenom);

        prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenomActionPerformed(evt);
            }
        });
        jPanel1.add(prenom);

        jLabel10.setFont(new java.awt.Font("Imprint MT Shadow", 3, 18)); // NOI18N
        jLabel10.setText("NUMERO PERSONNEL");
        jPanel1.add(jLabel10);
        jPanel1.add(jTextField8);

        jLabel9.setFont(new java.awt.Font("Imprint MT Shadow", 3, 18)); // NOI18N
        jLabel9.setText("NUMERO OFFICE");
        jPanel1.add(jLabel9);
        jPanel1.add(jTextField9);

        jLabel8.setFont(new java.awt.Font("Imprint MT Shadow", 3, 18)); // NOI18N
        jLabel8.setText("EMAIL");
        jPanel1.add(jLabel8);
        jPanel1.add(jTextField10);

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(1, 4));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Downloads\\icons8-py-26.png")); // NOI18N
        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setText("Modifier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton3.setText("supprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        jButton4.setText("Annuler");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel2.add(jTextField1);

        getContentPane().add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(1, 1));

        jTable1.setFont(new java.awt.Font("Wide Latin", 3, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "numero", "nom", "prenom", "numero perso", "numero Office", "emaill"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1);

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          Personne personne = new Personne();
          personne.setNom(nom.getText());
          personne.setPrenom(prenom.getText());
          personne.setNumBureau(jTextField8.getText());
          personne.setNumOffice(jTextField9.getText());
          personne.setEmail(jTextField10.getText());
          //personnes.add(personne);
          dbinstence.ajouter(personne);
          model= (DefaultTableModel) jTable1.getModel();
          model.addRow(personne.toObject());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void prenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenomActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(!jTable1.isRowSelected(row)){
            System.out.println("Aucune ligne n'est selectionnee");
           return; 
        }
        //personnes.remove(getSelectedPersonne());
        model.removeRow(row);
        selectedPersonne.setNom(nom.getText());
        selectedPersonne.setPrenom(prenom.getText());
        selectedPersonne.setNumBureau(jTextField8.getText());
        selectedPersonne.setNumOffice(jTextField9.getText());
        selectedPersonne.setEmail(jTextField10.getText());
        //personnes.add(selectedPersonne);
        dbinstence.update(row, selectedPersonne);
        model.insertRow(row, selectedPersonne.toObject());
//        personne.setNom(nom.getText());
//        personne.setPrenom(prenom.getText());
//        personne.setNumBureau(jTextField8.getText());
//        personne.setNumoffice(jTextField9.getText());
//        presonne.setEmail(jTextField10.getText());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(!jTable1.isRowSelected(row)){
            System.out.println("Aucune ligne n'est selectionnee");
           return; 
        }
       // personnes.remove(getSelectedPersonne());
       dbinstence.supprimer(row);
        model.removeRow(row);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        fillForm(getSelectedPersonne());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         nom.setText("");
        prenom.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        dbinstence.select();
    }//GEN-LAST:event_jButton4ActionPerformed
    public void fillTable(){
        model= (DefaultTableModel) jTable1.getModel();
        for(Personne personne:dbinstence.all()){
            model.addRow(personne.toObject());
        }
    }
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
            // TODO add your handling code here:
            /*
            List<RowFilter<Object,Object>> rf=new ArrayList();
            TableRowSorter<TableModel> sorter=new TableRowSorter(jTable1.getModel());
            jTable1.setRowSorter(sorter);
            RowFilter<Object,Object> andFilter = RowFilter.andFilter(rf);
            rf.add(RowFilter.regexFilter(jTextField1.getText(),0));
            sorter.setRowFilter(andFilter);
            */
            String requete=jTextField1.getText();
            filter(requete);
    }//GEN-LAST:event_jTextField1KeyReleased
    
    private void filter(String requete){
        TableRowSorter<DefaultTableModel> sorter=new TableRowSorter<DefaultTableModel>(model);
        jTable1.setRowSorter(sorter);
        sorter.setRowFilter(RowFilter.regexFilter(requete));
        
    }
            
    public Personne getSelectedPersonne(){
        selectedPersonne = new Personne();
        row = jTable1.getSelectedRow();
       // int columns = jTable1.getColumnCount();
       model = (DefaultTableModel) jTable1.getModel();
       selectedPersonne.setId(Integer.valueOf(jTable1.getValueAt(row, 0).toString()) );
        selectedPersonne.setNom(jTable1.getValueAt(row, 1).toString());
        selectedPersonne.setPrenom(jTable1.getValueAt(row, 2).toString());
        selectedPersonne.setNumBureau(jTable1.getValueAt(row, 3).toString());
        selectedPersonne.setNumOffice(jTable1.getValueAt(row, 4).toString());
        selectedPersonne.setEmail(jTable1.getValueAt(row, 5).toString());
        System.out.println("personne selectionner"+selectedPersonne);
        return selectedPersonne;
    }
    private void fillForm(Personne selectedPerson){
        nom.setText(selectedPerson.getNom());
        prenom.setText(selectedPerson.getPrenom());
        jTextField8.setText(selectedPerson.getNumBureau());
        jTextField9.setText(selectedPerson.getNumOffice());
        jTextField10.setText(selectedPerson.getEmail());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulaire().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lnom;
    private javax.swing.JLabel lprenom;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField prenom;
    // End of variables declaration//GEN-END:variables
}