/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CAGUI;

import carnetaddresse.Personne;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Administrator
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form form
     */
    DefaultTableModel model;
    private int row;
    Personne selectedPersonne;
    public Form(){
        initComponents();
        try{
            fillListTable();    
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        linfo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lnom = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        lprenom = new javax.swing.JLabel();
        prenom = new javax.swing.JTextField();
        lgenre = new javax.swing.JLabel();
        genre = new javax.swing.JTextField();
        lage = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        lperson = new javax.swing.JLabel();
        npersonnel = new javax.swing.JTextField();
        loffice = new javax.swing.JLabel();
        noffice = new javax.swing.JTextField();
        lemail = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        ajouter = new javax.swing.JButton();
        modifier = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        annuler = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listePersonne = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));

        linfo.setBackground(new java.awt.Color(204, 255, 204));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(new java.awt.GridLayout(3, 1));

        jPanel3.setLayout(new java.awt.GridLayout(7, 2));

        lnom.setText("Nom");
        jPanel3.add(lnom);

        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });
        nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomKeyReleased(evt);
            }
        });
        jPanel3.add(nom);

        lprenom.setText("Prenom");
        jPanel3.add(lprenom);
        jPanel3.add(prenom);

        lgenre.setText("genre");
        jPanel3.add(lgenre);
        jPanel3.add(genre);

        lage.setText("age");
        jPanel3.add(lage);
        jPanel3.add(age);

        lperson.setText("numero personnel");
        jPanel3.add(lperson);
        jPanel3.add(npersonnel);

        loffice.setText("numero office");
        jPanel3.add(loffice);
        jPanel3.add(noffice);

        lemail.setText("email");
        jPanel3.add(lemail);

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel3.add(email);

        jPanel2.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(3, 1));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(1, 5));

        ajouter.setBackground(new java.awt.Color(51, 204, 255));
        ajouter.setIcon(new javax.swing.ImageIcon("C:\\java\\CarnetAddresse\\src\\images\\ajouter.png")); // NOI18N
        ajouter.setText("Ajouter");
        ajouter.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });
        jPanel7.add(ajouter);

        modifier.setBackground(new java.awt.Color(51, 204, 255));
        modifier.setIcon(new javax.swing.ImageIcon("C:\\java\\CarnetAddresse\\src\\images\\modifier.png")); // NOI18N
        modifier.setText("Modifier");
        modifier.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });
        jPanel7.add(modifier);

        supprimer.setBackground(new java.awt.Color(51, 204, 255));
        supprimer.setIcon(new javax.swing.ImageIcon("C:\\java\\CarnetAddresse\\src\\images\\supprimer.png")); // NOI18N
        supprimer.setText("Supprimer");
        supprimer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });
        jPanel7.add(supprimer);

        annuler.setBackground(new java.awt.Color(51, 204, 255));
        annuler.setIcon(new javax.swing.ImageIcon("C:\\java\\CarnetAddresse\\src\\images\\annuler.png")); // NOI18N
        annuler.setText("Annuler");
        annuler.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });
        jPanel7.add(annuler);

        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField8KeyReleased(evt);
            }
        });
        jPanel7.add(jTextField8);

        jPanel4.add(jPanel7);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel8);

        jPanel2.add(jPanel4);

        listePersonne.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nom", "prenom", "genre", "age", "numero perso", "num office", "email"
            }
        ));
        listePersonne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listePersonneMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listePersonne);

        javax.swing.GroupLayout linfoLayout = new javax.swing.GroupLayout(linfo);
        linfo.setLayout(linfoLayout);
        linfoLayout.setHorizontalGroup(
            linfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        linfoLayout.setVerticalGroup(
            linfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, linfoLayout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\java\\CarnetAddresse\\src\\images\\profil.png")); // NOI18N
        jLabel1.setText("Gestion d'une personne");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(linfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(linfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        // TODO add your handling code here:
        if(!listePersonne.isRowSelected(row)){
            System.out.println("Aucune ligne n'est selectionnee");
           return; 
        }
        String delete = "DELETE from personne WHERE email = ?";
        try {
            PreparedStatement ps = connexion.connexion.getConnection().prepareStatement(delete);
            ps.setString(1, email.getText());
            ps.execute();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        model.removeRow(row);
        System.out.println("suppression avec succes");
    }//GEN-LAST:event_supprimerActionPerformed
    public void fillForm(Personne selectedPerson) {
        nom.setText(selectedPerson.getNom());
        prenom.setText(selectedPerson.getPrenom());
        genre.setText(selectedPerson.getGenre());
        age.setText(String.valueOf(selectedPerson.getAge()));
        npersonnel.setText(selectedPersonne.getNumBureau());
        noffice.setText(selectedPerson.getNumOffice());
        email.setText(selectedPerson.getEmail());
    }
    public Personne getSelectedPersonne(){
        selectedPersonne = new Personne();
        row = listePersonne.getSelectedRow();
        System.out.println(row);
       // int columns = jTable1.getColumnCount();
       model = (DefaultTableModel) listePersonne.getModel();
        selectedPersonne.setNom(listePersonne.getValueAt(row, 0).toString());
        selectedPersonne.setPrenom(listePersonne.getValueAt(row, 1).toString());
        selectedPersonne.setGenre(listePersonne.getValueAt(row, 2).toString());
        selectedPersonne.setAge(Integer.valueOf(listePersonne.getValueAt(row, 3).toString()));
        selectedPersonne.setNumBureau(listePersonne.getValueAt(row, 4).toString());
        selectedPersonne.setNumOffice(listePersonne.getValueAt(row, 5).toString());
        selectedPersonne.setEmail(listePersonne.getValueAt(row, 6).toString());
        System.out.println("personne "+selectedPersonne);
        return selectedPersonne;
    }
    public int control(){
        if(nom.getText().length()<4){
            JOptionPane.showMessageDialog(this, "le nom doit etre plus de 3 caracteres");
            return 0;
        }else if(prenom.getText().length()<4){
            JOptionPane.showMessageDialog(this, "le prenom doit etre plus de 3 caracteres");
            return 0;
        }else if(genre.getText().length()<1){
            JOptionPane.showMessageDialog(this, "le genre est obligatoire");
            return 0;
        }else if(age.getText().length()<1){
            JOptionPane.showMessageDialog(this, "saisisez correctement l'age");
            return 0;
        }
        return 1;
    }
     public void toEmpty(){
        nom.setText("");
        prenom.setText("");
        genre.setText("");
        age.setText("");
        npersonnel.setText("");
        noffice.setText("");
        email.setText("");
    }
    private void fillListTable() throws ClassNotFoundException, SQLException{
        String selectStatment = "SELECT * FROM personne";
        Statement st;
        ResultSet rs;
        st = connexion.connexion.getConnection().createStatement();
        rs = st.executeQuery(selectStatment);
        while(rs.next()){
            Personne personne = new Personne();
            personne.setNom(rs.getString("nom"));
            personne.setPrenom(rs.getString("prenom"));
            personne.setGenre(rs.getString("genre"));
            personne.setAge(Integer.parseInt(rs.getString("age")));
            personne.setNumBureau(rs.getString("numero_personnel"));
            personne.setNumOffice(rs.getString("numero_office"));
            personne.setEmail(rs.getString("email"));
            model = (DefaultTableModel) listePersonne.getModel();
            model.addRow(personne.toObject());
        }
    }
    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
        // TODO add your handling code here:
        if(control()==0) return;
        try{
            
            PreparedStatement ps = connexion.connexion.getConnection().prepareStatement("INSERT INTO personne(nom,prenom,numero_personnel,numero_office,email,age,genre) VALUES (?,?,?,?,?,?,?)");
            ps.setNString(1, nom.getText());
            ps.setNString(2, prenom.getText());
            ps.setNString(3, npersonnel.getText());
            ps.setNString(4, noffice.getText());
            ps.setNString(5, email.getText());
            ps.setInt(6, Integer.valueOf(age.getText()));
            ps.setNString(7, genre.getText());
            ps.execute();
        }catch(Exception e){
            e.printStackTrace();
        }
        
        Personne personne = new Personne();
        personne = editPersonne(personne, nom.getText(), prenom.getText(), genre.getText(), Integer.valueOf(age.getText()), npersonnel.getText(), noffice.getText(), email.getText());
        model = (DefaultTableModel) listePersonne.getModel();
        model.addRow(personne.toObject());
        System.out.println(personne);
    }//GEN-LAST:event_ajouterActionPerformed

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        // TODO add your handling code here:
        toEmpty();
        
    }//GEN-LAST:event_annulerActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        // TODO add your handling code here:
        if(control()==0) return;
        if(!listePersonne.isRowSelected(row)){
            System.out.println("Aucune ligne n'est selectionnee");
           return; 
        }
        try{
            String update = "UPDATE personne SET nom = ?, prenom = ?, numero_personnel = ?, numero_office = ?, age = ?, genre = ? WHERE  email = ?";
            PreparedStatement ps = connexion.connexion.getConnection().prepareStatement(update);
            ps.setString(1, nom.getText());
            ps.setString(2, prenom.getText());
            ps.setString(3, npersonnel.getText());
            ps.setString(4, noffice.getText());
            ps.setInt(5, Integer.parseInt(age.getText()));
            ps.setString(6, genre.getText());
            
            ps.setString(7, email.getText());
            ps.execute();
            if(ps.executeUpdate()==1){
                JOptionPane.showMessageDialog(null, "Mise a jour reussi");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        model.removeRow(row);
        selectedPersonne = editPersonne(selectedPersonne, nom.getText(), prenom.getText(), genre.getText(), Integer.valueOf(age.getText()), npersonnel.getText(), noffice.getText(), email.getText());
        model.insertRow(row,selectedPersonne.toObject());
    }//GEN-LAST:event_modifierActionPerformed

    private void listePersonneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listePersonneMouseClicked
        // TODO add your handling code here:
        fillForm(getSelectedPersonne());
    }//GEN-LAST:event_listePersonneMouseClicked

    private void jTextField8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyReleased
        // TODO add your handling code here:
        String requete=jTextField8.getText();
        filter(requete);
    }//GEN-LAST:event_jTextField8KeyReleased

    private void nomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_nomKeyReleased

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed
    private void filter(String requete){
        TableRowSorter<DefaultTableModel> sorter=new TableRowSorter<DefaultTableModel>(model);
        listePersonne.setRowSorter(sorter);
        sorter.setRowFilter(RowFilter.regexFilter(requete));
        
    }
    private Personne editPersonne(Personne p,String nom, String prenom,String genre,int age, String numBureau, String numOffice, String email){
        p.setNom(nom);
        p.setPrenom(prenom);
        p.setGenre(genre);
        p.setAge(age);
        p.setNumBureau(numBureau);
        p.setNumOffice(numOffice);
        p.setEmail(email);
        return p;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JButton ajouter;
    private javax.swing.JButton annuler;
    private javax.swing.JTextField email;
    private javax.swing.JTextField genre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel lage;
    private javax.swing.JLabel lemail;
    private javax.swing.JLabel lgenre;
    private javax.swing.JPanel linfo;
    private javax.swing.JTable listePersonne;
    private javax.swing.JLabel lnom;
    private javax.swing.JLabel loffice;
    private javax.swing.JLabel lperson;
    private javax.swing.JLabel lprenom;
    private javax.swing.JButton modifier;
    private javax.swing.JTextField noffice;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField npersonnel;
    private javax.swing.JTextField prenom;
    private javax.swing.JButton supprimer;
    // End of variables declaration//GEN-END:variables
}
